version: '3.8'

services:
  web:
    image: deeali779/data-text-pipeline:latest
    container_name: data-text-pipeline
    ports:
      - "${WEB_PORT:-8501}:8501"
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - ./.cache:/app/.cache
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped