services:
  - type: web
    name: data-text-pipeline
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 8501
    healthCheckPath: /_stcore/health